Create nft-rfc-008.md
interNFT/nft-rfc pull request #10
Opened 2021-01-21 08:02 UTC by eric-schuh

Adding first, working draft of nft-rfc-008.

2021-01-21 14:26 UTC, jandrieu commented
For consistency with the layer model, the title should probably be NFT-RFC-008 NFT Assertions

2021-01-21 14:28 UTC, jandrieu commented on nft-rfc-008.md
> +title: NFT Resource Verification
title: NFT Assertions

2021-01-21 14:28 UTC, jandrieu commented on nft-rfc-008.md
> +# NFT RFC 008 NFT Resource Verification
# NFT RFC 008 NFT Assertions

2021-01-28 14:06 UTC, ig-shaun requested changes
Needs to be updated with the redraft from Docs.

2021-01-28 14:06 UTC, ig-shaun commented on nft-rfc-008.md
> +title: NFT Resource Verification
Change title to NFT Assertions

2021-01-28 15:54 UTC, ig-shaun approved these changes
Good first draft

2021-01-28 15:54 UTC, merged