First draft of rfc9
interNFT/nft-rfc pull request #16
Opened 2021-03-18 14:34 UTC by jandrieu

2021-04-01 01:16 UTC, jandrieu commented
@ig-shaun Please review and merge.

2021-04-09 10:12 UTC, ig-shaun requested changes

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +blockchain-based assets such as tokens, smart contracts, and addresses.
```suggestion
specifically designed to refer to on-chain assets, such as NFTs, fungible tokens, namespace records and wallets.
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +[[1]](#ref1), IIDs are 100% conformant DIDs; IIDs ***are*** DIDs and IID
```suggestion
[[1]](#ref1), IIDs are fully conformant DIDs and therefore ***are*** DIDs. IID
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +documents are DID documents. The IID specification also provides
```suggestion
documents are DID documents. The IID specification provides
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +additional features designed for on-chain assets, such as the ability to
```suggestion
additional features which are purpose-designed for describing and interacting with on-chain assets. Such as Linked Resources, which enable
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +verifiably yet privately associate arbitrary digital or real-world
```suggestion
arbitrary digital or real-world resources to be verifiably, but privately, associated with
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +assets with the underlying IID Subject. IIDs also constrain compatible
```suggestion
the digital asset, which is the IID Subject.
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +DID methods in particular ways, including a restriction on the DID
```suggestion
When referring to an IID, it is implicit that this identifies an on-chain asset. This constraint has the advantage that IID's are self-referential. Which overcomes the HTTP Range14 problem of DIDs which refer to resources that cannot be located at an end-point, such as a physical object. DID Methods which conform to this IID specification MUST resolve to a uniquely identified digital asset, within a unique blockchain namespace.
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +Subject---IID Subjects MUST be on-chain resources. Any DID method that
```suggestion

```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +meets the requirements in this specification ***is*** an IID method, and
```suggestion

```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +its IIDs ***are*** DIDs. Any DID software that is conformant to the W3C
```suggestion
Any software application using DIDs which conform to the W3C DID-Core
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +specification SHOULD be able to work with IIDs and IID documents,
```suggestion
specification SHOULD be able to operate with IIDs and IID documents.
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +although some IID-specific features may require additional support.
```suggestion
Although some IID-specific features may require additional support. For instance, to dereference Linked Resources.
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +resources. Non-fungible tokens (NFTs) require a cryptographically secure
```suggestion
resources. On-chain digital assets require a cryptographically secure
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +means to both refer to specific tokens and prove control or ownership
```suggestion
mechanisms for referring to the asset and to prove control or ownership of the asset,
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +
All on-chain digital assets MUST have a unique identifier which can be dereferenced to locate the asset as a resource located in a specific chain namespace.

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +We refer to this new class of identifiers as Interchain Identifiers, or
```suggestion
We refer to this new class of identifiers as Interchain Identifiers (IIDs).
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +IIDs for short. We propose this new identifier would be appropriate for
```suggestion
Interchain Identifiers SHOULD be appropriate for
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +any on-chain asset, including smart contracts, fungible tokens, and
```suggestion
identifying and referring to any on-chain asset. Including smart contracts, fungible tokens,
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +non-fungible tokens.
```suggestion
non-fungible tokens, namespace records, and wallets.
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +IIDs build on a foundation of global identifiers dating back to Uniform
```suggestion
IIDs build on a foundation of Internet identifiers, dating back to Uniform
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +foundation of the World Wide Web. URLs and URIs allow for different
```suggestion
foundation of the World Wide Web. URIs allow for different
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +schemes that specify particular mechanisms for interpreting and applying
```suggestion
to specify the mechanisms for interpreting and applying
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +to provide a class of identifiers one can verify without reliance on a
```suggestion
to provide a class of identifiers which can verified without reliance on a
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +verification methods like public/private key cryptography on any number
```suggestion
verification methods, such as public-private cryptographic keys derived from any number
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +of curves, which in turn are used for verification relationships like
```suggestion
of curves. These keys are used to establish verification relationships for the purpose of
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +invocation. When one uses a DID for those relationships, a verifying
```suggestion
invocation. A DID Method establishes these verification relationships in a way that each cryptographic method is associated with its specific purpose. 
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +authentication, assertion, capability delegation, and capability
```suggestion
authentication, assertion, capability delegation, or capability
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +party can use cryptographic material associated with the DID to verify
```suggestion

```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +the use is appropriate. DID-URLs extend the base DID syntax to support
```suggestion
DID-URLs extend the base DID syntax to support 
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +```/path``` and ```#fragment``` parts of URLs to refer to IID References
```suggestion
```/path``` and ```#fragment``` parts of URLs for IID References 
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +We describe how IIDs and DIDs relate in section [IIDs as DIDs](#IIDs-as-DIDs).
```suggestion
The relationship between IIDs and DIDs is further described in the [IIDs as DIDs](#IIDs-as-DIDs) section.
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +off-chain resources, whether digital, real-world, or conceptual. In this
```suggestion
off-chain resources. Whether these resources are digital, physical, or conceptual. To achieve this
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +role, IIDs rely on content-based identifiers and content-based
```suggestion
IID methods SHOULD use content-based identifiers and content-based
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +addressing systems, where a hash of the digital asset is used to
```suggestion
addressing systems, in which a hash of linked resource is used to
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +unambiguously verify the asset is the intended resource. Standards like
```suggestion
unambiguously verify the resource. Standards such as
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +and representations. Approaches using merkle trees can turn hashes into
```suggestion
and representations.
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +a hashgraphs, allowing an arbitrary number of resources to be
```suggestion
Using mechanisms such as Hashgraphs enables an arbitrary number of verifiable resources to be linked to a digital asset, without even revealing the number of resources.
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +independently verified without revealing even the number of those assets
```suggestion
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +publicly. These content identifiers can provide robust verifiability no
```suggestion
Content Identifiers (CIDs) provide robust verifiability and enable resources to be addressed without path-dependency. These mechanisms enable rich data to be associated with digital resources, without compromising privacy.
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +matter where such resources might be located or retrieved.
```suggestion
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +Specifically for NFTs, IIDs allow you to
```suggestion
Implementing IIDs allows tokenized digital assets to be:
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +
```suggestion
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +
```suggestion
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +1. Identify individual NFTs as well as their token class
```suggestion
1. Identified as unique digital assets that belong to a specific class of tokens. 
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +2. Identify resources associated with that NFT
```suggestion
2. Linked to verifiable on-chain and off-chain resources.
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +
```suggestion
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +
```suggestion
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +3. Exercise rights related to those resources using cryptography anchored to the NFT
```suggestion
3. Accorded rights in relation to both the token and its linked resources. Including executable rights, which may be issued and delegated off-chain using a mechanism such as Authorization Capabilities (zCaps), to access, invoke and transact with specific on-chain or off-chain services.
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +IIDs allow these functions a manner that addresses the privacy
```suggestion
4. Afforded privacy in relation to the token's metadata. Including what the token represents, the associated services which can be invoked, and the resources which are linked to the token.
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +requirements for such references, with flexible support for use cases
```suggestion
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +that need to make different choices. Our approach offers a robust,
```suggestion
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +flexible, and capable identifier mechanism for NFTs, and on-chain
```suggestion
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +assets, of all types.
```suggestion
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +This specification was designed for Non-Fungible Tokens. NFT-RFC-002
```suggestion
The IID specification was designed to address the requirements for Non-Fungible Token (NFT) use-cases, which are described in NFT-RFC-002.
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +[[4]](#ref4) describes the range of types of tokens as well as several detailed
```suggestion
[[4]](#ref4).
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +user stories covered by this work. NFT-RFC-008 [[5]](#ref5) describes how one
```suggestion
The specific use-case of tokenizing Renewable Energy Certificates (RECs), described in NFT-RFC-008 [[5]](#ref5) demonstrates how IIDs can be used together with DID-related W3C specifications for
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +might apply IIDs, Verifiable Credentials, and Authorization Capabilities to define,
```suggestion
Verifiable Credentials (VCs) and Authorization Capabilities (zCaps), to define a class of tokens (REC-2021),
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +authorize, issue, use, and sell NFT-based Renewable Energy Certificates
```suggestion
authorize the issuance of verifiable credentials, verify claims of renewable energy production, and then mint and trade Renewable Energy Certificates as NFTs. With accorded rights and linked resources.
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +(RECs) according to an REC 2021 standard.
```suggestion
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +
```suggestion
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +Throughout this document we use the REC2021 use case for examples. In summary:
```suggestion
Throughout this document we use the REC2021 use case for examples. 
In summary:
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +   a) the ability to create Certification Reports (with certain
```suggestion
   a) the capability to create Certification Reports (with certain
```

2021-04-09 10:12 UTC, ig-shaun commented on nft_rfc_009.md
> +   b) the ability to mint REC2021 tokens (with certain constraints)
```suggestion
   b) the capability to mint REC2021 tokens (with certain constraints)
```

2021-04-10 21:40 UTC, jandrieu commented on nft_rfc_009.md
> +
```suggestion
All on-chain digital assets MUST have a unique identifier which can be dereferenced to locate the asset as a resource located in a specific chain namespace.
```

2021-04-10 21:41 UTC, merged